export const portfolioData = {
	profile: {
		name: `Achyutam Sharma`,
		title: `Data Analyst & Full-Stack Developer`,
		subtitle: `MCA Graduate · KIIT University · Building Data-Driven Solutions`,
		bio: `Passionate about turning complex data into actionable insights. I blend analytical thinking with full-stack development expertise to craft solutions that matter. Specialized in Python data analysis, Power BI, and modern web technologies.`,
		email: `akshubusiness187@gmail.com`,
		phone: `+91 XXXXXXXXXX`,
		location: `Jharkhand, India`,
		instagram: `https://instagram.com/akshutam_here`,
		linkedin: `https://www.linkedin.com/in/achyutam-sharma/`,
		github: `https://github.com/AchyutamSharma`,
		avatar: ``,
		resumeUrl: ``,
		yearsExp: 1,
		projectsCount: 5,
		techCount: 12,
	},
	projects: [
		{
			id: `1`,
			title: `Diwali Sales Analysis`,
			description: `Comprehensive EDA on Diwali sales dataset revealing consumer patterns and revenue trends.`,
			longDescription: `Performed end-to-end exploratory data analysis on a 11,000+ row Diwali sales dataset. Used Pandas for data wrangling, Seaborn & Matplotlib for visualization. Uncovered key buyer demographics, top product categories, and state-wise revenue insights.`,
			image: ``,
			tags: [`Python`, `Pandas`, `Seaborn`, `EDA`, `Matplotlib`],
			github: `https://github.com/`,
			demo: `#`,
			category: `data`,
			featured: true,
		},
		{
			id: `2`,
			title: `AgroVision – Plant Disease Detector`,
			description: `AI-powered plant disease detection using CNN with a full web interface.`,
			longDescription: `Built a plant disease detection system using a pre-trained CNN model. Features a React.js frontend with image upload capability, Flask backend serving the model, and 95%+ detection accuracy across 38 plant disease classes.`,
			image: ``,
			tags: [`Python`, `CNN`, `Flask`, `React`, `TensorFlow`],
			github: `https://github.com/`,
			demo: `#`,
			category: `ml`,
			featured: true,
		},
		{
			id: `3`,
			title: `Portfolio`,
			description: `Full-stack portfolio website with Gemini AI chatbot, admin dashboard, project management, and responsive modern UI.`,
			longDescription: `Built a full-stack portfolio website using React, Vite, Express.js, and Gemini AI. Features include an AI chatbot, admin dashboard, project management, responsive design, and custom domain deployment.`,
			image: ``,
			tags: [`React`, `Vite`, `Tailwind CSS`, `Express.js`, `REST API`, `Gemini API`, `Artificial Intelligence`, `Chatbot Development`, `Responsive Web Design`, `Full-Stack Development`],
			github: `https://github.com/new-portfolio-2026`,
			demo: `https://akshutam.app`,
			category: `web`,
			featured: false,
		},
	],
	skills: [
		{ name: `Python`, level: 75, category: `language`, icon: `🐍` },
		{ name: `SQL`, level: 60, category: `language`, icon: `🗄️` },
		{ name: `JavaScript`, level: 75, category: `language`, icon: `⚡` },
		{ name: `HTML/CSS`, level: 85, category: `language`, icon: `🎨` },
		{ name: `Pandas`, level: 75, category: `framework`, icon: `🐼` },
		{ name: `NumPy`, level: 75, category: `framework`, icon: `🔢` },
		{ name: `React`, level: 60, category: `framework`, icon: `⚛️` },
		{ name: `Node.js`, level: 60, category: `framework`, icon: `🟢` },
		{ name: `Express.js`, level: 60, category: `framework`, icon: `🚂` },
		{ name: `Power BI`, level: 60, category: `tool`, icon: `📊` },
		{ name: `Matplotlib`, level: 75, category: `tool`, icon: `📈` },
		{ name: `Seaborn`, level: 65, category: `tool`, icon: `🌊` },
		{ name: `MongoDB`, level: 65, category: `database`, icon: `🍃` },
		{ name: `MySQL`, level: 60, category: `database`, icon: `🐬` },
	],
	education: [
		{
			id: `1`,
			degree: `Master of Computer Applications (MCA)`,
			institution: `KIIT University`,
			year: `2024 – 2026`,
			gpa: `7.21 CGPA`,
			description: `Specialized in Data Analytics and Full-Stack Development. Coursework included Machine Learning, AI, Data Structures, and Software Engineering.`,
			location: `Bhubaneswar, Odisha`,
		},
		{
			id: `2`,
			degree: `Bachelor of Computer Applications (BCA)`,
			institution: `SB College of Management Studies`,
			year: `2020 – 2024`,
			gpa: `6.5 CGPA`,
			description: `Completed Bachelor of Computer Applications (BCA) from S.B. College of Management Studies, affiliated with Bangalore City University. Gained foundational knowledge in programming, database management, software development, computer networks, and web technologies through academic coursework and practical projects.`,
			location: `Bangalore, India`,
		},
	],
	certificates: [],
};
